package test.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "bookTable".
 */
public class Book {

    private Long id;
    /** Not-null value. */
    private String bookid;
    private String bookName;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, String bookid, String bookName) {
        this.id = id;
        this.bookid = bookid;
        this.bookName = bookName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBookid() {
        return bookid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookid(String bookid) {
        this.bookid = bookid;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

}
