package test.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ImUserTable".
 */
public class ImUserInfo {

    private Long id;
    /** Not-null value. */
    private String userId;
    private String userName;
    private String userIcon;
    private String tag;
    private String userRemarks;
    private Boolean isShield;

    public ImUserInfo() {
    }

    public ImUserInfo(Long id) {
        this.id = id;
    }

    public ImUserInfo(Long id, String userId, String userName, String userIcon, String tag, String userRemarks, Boolean isShield) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.userIcon = userIcon;
        this.tag = tag;
        this.userRemarks = userRemarks;
        this.isShield = isShield;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserIcon() {
        return userIcon;
    }

    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getUserRemarks() {
        return userRemarks;
    }

    public void setUserRemarks(String userRemarks) {
        this.userRemarks = userRemarks;
    }

    public Boolean getIsShield() {
        return isShield;
    }

    public void setIsShield(Boolean isShield) {
        this.isShield = isShield;
    }

}
