package test.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import test.greendao.bean.ImUserInfo;
import test.greendao.bean.Book;

import test.greendao.dao.ImUserInfoDao;
import test.greendao.dao.BookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imUserInfoDaoConfig;
    private final DaoConfig bookDaoConfig;

    private final ImUserInfoDao imUserInfoDao;
    private final BookDao bookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imUserInfoDaoConfig = daoConfigMap.get(ImUserInfoDao.class).clone();
        imUserInfoDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        imUserInfoDao = new ImUserInfoDao(imUserInfoDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);

        registerDao(ImUserInfo.class, imUserInfoDao);
        registerDao(Book.class, bookDao);
    }
    
    public void clear() {
        imUserInfoDaoConfig.getIdentityScope().clear();
        bookDaoConfig.getIdentityScope().clear();
    }

    public ImUserInfoDao getImUserInfoDao() {
        return imUserInfoDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

}
